### 회원가입
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username": "admin",
  "password": "abc1234!",
  "roles": "ROLE_ADMIN",
  "email": "22rkdmin@naver.com"
}

### 로그인
POST http://localhost:8080/member/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "abc1234!"
}

### test
GET http://localhost:8080/member/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiUk9MRV9BRE1JTiIsImlhdCI6MTY2Njk4MjYxMiwiZXhwIjoxNjY2OTg2MjEyfQ.7EzXMyvOvu4GoKZrtYub-iE3zwvNO3v4QqrTPXZyeQnFDEEq1HHjYHKeO9q7ZWtfjUK_734biSV6XpOpsti5hQ
Accept: application/json