### 회원가입
POST http://localhost:8080/member/signup
Content-Type: application/json

{
  "username": "admin12",
  "password": "abc1234!",
  "roles": "ROLE_MANAGER",
  "email": "22rkdmin@nav2er.com"
}

### 로그인
POST http://localhost:8080/member/signin
Content-Type: application/json

{
  "username": "admin12",
  "password": "abc1234!"
}

### 이메일 인증
GET http://localhost:8080/member/email/20f0aacf-5b98-4cdd-a299-e78ecb041e93
Accept: application/json

