### 상품 등록(매니저, 관리자)
POST http://localhost:8080/item/register/admin-manager
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiUk9MRV9BRE1JTiIsImlhdCI6MTY2NzY0NTkzNiwiZXhwIjoxNjY3NjQ5NTM2fQ.820kdjKi9AdT3wScdgcOIYzDjU7G4fuMI7962gVAkEzeWke_DOSaLYU6BfYHjELSYh56TBmHo1ChQCaicHWaJQ
Content-Type: application/json

{
  "itemName": "상품이름21",
  "url" : "url",
  "price" : 1000,
  "saleRate" : 10,
  "content" : "내용1",
  "cnt" : 10,
  "brandId" : 1,
  "sellerId" : 1,
  "modelId" : 1,
  "regItemInfo" : {
    "material" : "소재",
    "colorList" : [
      "red"
    ],
    "sizeList" : [
      "xl", "xxl"
    ]
  },
  "categoryNameList" : [
    "신발"
  ]
}

### 상품 조회
GET http://localhost:8080/item/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiUk9MRV9BRE1JTiIsImlhdCI6MTY2NzY0NTkzNiwiZXhwIjoxNjY3NjQ5NTM2fQ.820kdjKi9AdT3wScdgcOIYzDjU7G4fuMI7962gVAkEzeWke_DOSaLYU6BfYHjELSYh56TBmHo1ChQCaicHWaJQ
Accept: application/json

